// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package db

import (
	"context"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (name, address, phone)
VALUES ($1, $2, $3)
RETURNING id, name, address, phone, active, created_at
`

type CreateBranchParams struct {
	Name    string  `json:"name"`
	Address *string `json:"address"`
	Phone   *string `json:"phone"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch, arg.Name, arg.Address, arg.Phone)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getBranch = `-- name: GetBranch :one
SELECT id, name, address, phone, active, created_at
FROM branches
WHERE id = $1
`

func (q *Queries) GetBranch(ctx context.Context, id string) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listAllBranches = `-- name: ListAllBranches :many
SELECT id, name, address, phone, active, created_at
FROM branches
ORDER BY name
`

// Todas (activas e inactivas). La usa el owner en la pantalla de gestión.
func (q *Queries) ListAllBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listAllBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranches = `-- name: ListBranches :many

SELECT id, name, address, phone, active, created_at
FROM branches
WHERE active = true
ORDER BY name
`

// Queries para el recurso branches (sucursales).
// Solo activas. La usan el POS, el dashboard y el inventario.
func (q *Queries) ListBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBranchActive = `-- name: SetBranchActive :one
UPDATE branches SET active = $2 WHERE id = $1 RETURNING id, name, address, phone, active, created_at
`

type SetBranchActiveParams struct {
	ID     string `json:"id"`
	Active bool   `json:"active"`
}

func (q *Queries) SetBranchActive(ctx context.Context, arg SetBranchActiveParams) (Branch, error) {
	row := q.db.QueryRow(ctx, setBranchActive, arg.ID, arg.Active)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches
SET
  name    = COALESCE($1, name),
  address = COALESCE($2, address),
  phone   = COALESCE($3, phone)
WHERE id = $4
RETURNING id, name, address, phone, active, created_at
`

type UpdateBranchParams struct {
	Name    *string `json:"name"`
	Address *string `json:"address"`
	Phone   *string `json:"phone"`
	ID      string  `json:"id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.ID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
