// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"
)

const listInventoryByBranch = `-- name: ListInventoryByBranch :many
SELECT
  p.id            AS product_id,
  p.name          AS product_name,
  p.category,
  p.price,
  COALESCE(i.current_stock, 0)::int AS current_stock,
  COALESCE(i.min_stock, 0)::int     AS min_stock
FROM products p
LEFT JOIN inventory i ON i.product_id = p.id AND i.branch_id = $1
WHERE p.active = true
ORDER BY p.name
`

type ListInventoryByBranchRow struct {
	ProductID    string          `json:"product_id"`
	ProductName  string          `json:"product_name"`
	Category     ProductCategory `json:"category"`
	Price        string          `json:"price"`
	CurrentStock int32           `json:"current_stock"`
	MinStock     int32           `json:"min_stock"`
}

// Todos los productos activos con su stock y mínimo en la sucursal dada.
// LEFT JOIN: incluye productos SIN renglón de inventario aún (stock/min = 0).
func (q *Queries) ListInventoryByBranch(ctx context.Context, branchID string) ([]ListInventoryByBranchRow, error) {
	rows, err := q.db.Query(ctx, listInventoryByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryByBranchRow
	for rows.Next() {
		var i ListInventoryByBranchRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.Category,
			&i.Price,
			&i.CurrentStock,
			&i.MinStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellableProducts = `-- name: ListSellableProducts :many

SELECT
  p.id,
  p.name,
  p.category,
  p.price,
  i.current_stock AS stock
FROM products p
JOIN inventory i ON i.product_id = p.id AND i.branch_id = $1
WHERE p.active = true
ORDER BY p.name
`

type ListSellableProductsRow struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Category ProductCategory `json:"category"`
	Price    string          `json:"price"`
	Stock    int32           `json:"stock"`
}

// Queries de inventario (usadas por el POS para mostrar productos con stock).
// Productos activos con su stock en la sucursal dada.
// El front los usa en el POS para mostrar precio y disponibilidad.
func (q *Queries) ListSellableProducts(ctx context.Context, branchID string) ([]ListSellableProductsRow, error) {
	rows, err := q.db.Query(ctx, listSellableProducts, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSellableProductsRow
	for rows.Next() {
		var i ListSellableProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restockInventory = `-- name: RestockInventory :one
INSERT INTO inventory (product_id, branch_id, current_stock, min_stock)
VALUES ($1, $2, $3, 0)
ON CONFLICT (product_id, branch_id)
DO UPDATE SET current_stock = inventory.current_stock + EXCLUDED.current_stock,
              updated_at    = now()
RETURNING id, product_id, branch_id, current_stock, min_stock, updated_at
`

type RestockInventoryParams struct {
	ProductID string `json:"product_id"`
	BranchID  string `json:"branch_id"`
	Qty       int32  `json:"qty"`
}

// Suma una entrada de stock. UPSERT: crea el renglón si el producto aún no tiene
// inventario en esa sucursal (ej. producto recién creado por el CRUD).
func (q *Queries) RestockInventory(ctx context.Context, arg RestockInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, restockInventory, arg.ProductID, arg.BranchID, arg.Qty)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.CurrentStock,
		&i.MinStock,
		&i.UpdatedAt,
	)
	return i, err
}

const setMinStock = `-- name: SetMinStock :one
INSERT INTO inventory (product_id, branch_id, current_stock, min_stock)
VALUES ($1, $2, 0, $3)
ON CONFLICT (product_id, branch_id)
DO UPDATE SET min_stock  = EXCLUDED.min_stock,
              updated_at = now()
RETURNING id, product_id, branch_id, current_stock, min_stock, updated_at
`

type SetMinStockParams struct {
	ProductID string `json:"product_id"`
	BranchID  string `json:"branch_id"`
	MinStock  int32  `json:"min_stock"`
}

// Fija el stock mínimo (umbral de alerta). UPSERT por la misma razón que restock.
func (q *Queries) SetMinStock(ctx context.Context, arg SetMinStockParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, setMinStock, arg.ProductID, arg.BranchID, arg.MinStock)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.CurrentStock,
		&i.MinStock,
		&i.UpdatedAt,
	)
	return i, err
}
