// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type PaymentMethod string

const (
	PaymentMethodCash     PaymentMethod = "cash"
	PaymentMethodCard     PaymentMethod = "card"
	PaymentMethodTransfer PaymentMethod = "transfer"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type ProductCategory string

const (
	ProductCategoryPaleta     ProductCategory = "paleta"
	ProductCategoryNieve      ProductCategory = "nieve"
	ProductCategoryAguaFresca ProductCategory = "agua_fresca"
	ProductCategoryOtro       ProductCategory = "otro"
)

func (e *ProductCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductCategory(s)
	case string:
		*e = ProductCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductCategory: %T", src)
	}
	return nil
}

type NullProductCategory struct {
	ProductCategory ProductCategory `json:"product_category"`
	Valid           bool            `json:"valid"` // Valid is true if ProductCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ProductCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductCategory), nil
}

type SaleStatus string

const (
	SaleStatusCompleted SaleStatus = "completed"
	SaleStatusCancelled SaleStatus = "cancelled"
)

func (e *SaleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SaleStatus(s)
	case string:
		*e = SaleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SaleStatus: %T", src)
	}
	return nil
}

type NullSaleStatus struct {
	SaleStatus SaleStatus `json:"sale_status"`
	Valid      bool       `json:"valid"` // Valid is true if SaleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSaleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SaleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SaleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSaleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SaleStatus), nil
}

type UserRole string

const (
	UserRoleOwner    UserRole = "owner"
	UserRoleManager  UserRole = "manager"
	UserRoleEmployee UserRole = "employee"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Branch struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Address   *string   `json:"address"`
	Phone     *string   `json:"phone"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
}

type Inventory struct {
	ID           string    `json:"id"`
	ProductID    string    `json:"product_id"`
	BranchID     string    `json:"branch_id"`
	CurrentStock int32     `json:"current_stock"`
	MinStock     int32     `json:"min_stock"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Product struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Category  ProductCategory `json:"category"`
	Price     string          `json:"price"`
	Active    bool            `json:"active"`
	CreatedAt time.Time       `json:"created_at"`
}

type Sale struct {
	ID            string        `json:"id"`
	BranchID      string        `json:"branch_id"`
	UserID        string        `json:"user_id"`
	Total         string        `json:"total"`
	PaymentMethod PaymentMethod `json:"payment_method"`
	Status        SaleStatus    `json:"status"`
	CreatedAt     time.Time     `json:"created_at"`
}

type SaleItem struct {
	ID          string `json:"id"`
	SaleID      string `json:"sale_id"`
	ProductID   string `json:"product_id"`
	ProductName string `json:"product_name"`
	UnitPrice   string `json:"unit_price"`
	Quantity    int32  `json:"quantity"`
	Subtotal    string `json:"subtotal"`
}

type User struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         UserRole  `json:"role"`
	BranchID     *string   `json:"branch_id"`
	Active       bool      `json:"active"`
	CreatedAt    time.Time `json:"created_at"`
}
