// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, category, price)
VALUES ($1, $2, $3::numeric)
RETURNING id, name, category, price, active, created_at
`

type CreateProductParams struct {
	Name     string          `json:"name"`
	Category ProductCategory `json:"category"`
	Price    string          `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Category, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, category, price, active, created_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many

SELECT id, name, category, price, active, created_at
FROM products
WHERE
  ($1::boolean IS NULL OR active = $1)
  AND ($2::product_category IS NULL OR category = $2)
ORDER BY name
`

type ListProductsParams struct {
	Active   *bool            `json:"active"`
	Category *ProductCategory `json:"category"`
}

// Queries para el recurso products.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Active, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductActive = `-- name: SetProductActive :one
UPDATE products SET active = $2 WHERE id = $1 RETURNING id, name, category, price, active, created_at
`

type SetProductActiveParams struct {
	ID     string `json:"id"`
	Active bool   `json:"active"`
}

func (q *Queries) SetProductActive(ctx context.Context, arg SetProductActiveParams) (Product, error) {
	row := q.db.QueryRow(ctx, setProductActive, arg.ID, arg.Active)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
  name     = COALESCE($1, name),
  category = COALESCE($2::product_category, category),
  price    = COALESCE($3::text::numeric, price)
WHERE id = $4
RETURNING id, name, category, price, active, created_at
`

type UpdateProductParams struct {
	Name     *string          `json:"name"`
	Category *ProductCategory `json:"category"`
	Price    *string          `json:"price"`
	ID       string           `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Category,
		arg.Price,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
