// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"
)

const criticalStock = `-- name: CriticalStock :many
SELECT
  i.product_id,
  p.name          AS product_name,
  p.category::text AS category,
  i.branch_id,
  b.name          AS branch_name,
  i.current_stock,
  i.min_stock
FROM inventory i
JOIN products  p ON p.id = i.product_id
JOIN branches  b ON b.id = i.branch_id
WHERE i.current_stock <= i.min_stock
  AND p.active = true
  AND b.active = true
  AND ($1::uuid IS NULL OR i.branch_id = $1)
ORDER BY i.current_stock ASC, p.name
`

type CriticalStockRow struct {
	ProductID    string `json:"product_id"`
	ProductName  string `json:"product_name"`
	Category     string `json:"category"`
	BranchID     string `json:"branch_id"`
	BranchName   string `json:"branch_name"`
	CurrentStock int32  `json:"current_stock"`
	MinStock     int32  `json:"min_stock"`
}

// Productos cuyo stock actual está en o por debajo del mínimo.
func (q *Queries) CriticalStock(ctx context.Context, branchID *string) ([]CriticalStockRow, error) {
	rows, err := q.db.Query(ctx, criticalStock, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CriticalStockRow
	for rows.Next() {
		var i CriticalStockRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.Category,
			&i.BranchID,
			&i.BranchName,
			&i.CurrentStock,
			&i.MinStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailySummary = `-- name: DailySummary :one

SELECT
  COUNT(*)::int                    AS sale_count,
  COALESCE(SUM(total), 0)::text    AS total_revenue,
  COALESCE(SUM(
    (SELECT SUM(quantity) FROM sale_items si WHERE si.sale_id = s.id)
  ), 0)::int                       AS items_sold
FROM sales s
WHERE status = 'completed'
  AND created_at >= $1::timestamptz
  AND created_at <  $2::timestamptz
  AND ($3::uuid IS NULL OR branch_id = $3)
`

type DailySummaryParams struct {
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
	BranchID *string   `json:"branch_id"`
}

type DailySummaryRow struct {
	SaleCount    int32  `json:"sale_count"`
	TotalRevenue string `json:"total_revenue"`
	ItemsSold    int32  `json:"items_sold"`
}

// Queries de reportes: ventas del día, top productos, stock crítico.
// Total de ventas del día para una sucursal (o todas si branch_id es NULL).
func (q *Queries) DailySummary(ctx context.Context, arg DailySummaryParams) (DailySummaryRow, error) {
	row := q.db.QueryRow(ctx, dailySummary, arg.DateFrom, arg.DateTo, arg.BranchID)
	var i DailySummaryRow
	err := row.Scan(&i.SaleCount, &i.TotalRevenue, &i.ItemsSold)
	return i, err
}

const topProducts = `-- name: TopProducts :many
SELECT
  si.product_id,
  si.product_name,
  p.category::text                        AS category,
  SUM(si.quantity)::int                   AS total_qty,
  SUM(si.subtotal)::text                  AS total_revenue
FROM sale_items si
JOIN products p  ON p.id  = si.product_id
JOIN sales    s  ON s.id  = si.sale_id
WHERE s.status = 'completed'
  AND s.created_at >= $1::timestamptz
  AND s.created_at <  $2::timestamptz
  AND ($3::uuid IS NULL OR s.branch_id = $3)
GROUP BY si.product_id, si.product_name, p.category
ORDER BY total_qty DESC
LIMIT $4
`

type TopProductsParams struct {
	DateFrom time.Time `json:"date_from"`
	DateTo   time.Time `json:"date_to"`
	BranchID *string   `json:"branch_id"`
	Lim      int32     `json:"lim"`
}

type TopProductsRow struct {
	ProductID    string `json:"product_id"`
	ProductName  string `json:"product_name"`
	Category     string `json:"category"`
	TotalQty     int32  `json:"total_qty"`
	TotalRevenue string `json:"total_revenue"`
}

// Top N productos por cantidad vendida en el rango de fechas.
func (q *Queries) TopProducts(ctx context.Context, arg TopProductsParams) ([]TopProductsRow, error) {
	rows, err := q.db.Query(ctx, topProducts,
		arg.DateFrom,
		arg.DateTo,
		arg.BranchID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopProductsRow
	for rows.Next() {
		var i TopProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.Category,
			&i.TotalQty,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
