// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package db

import (
	"context"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (branch_id, user_id, total, payment_method)
VALUES (
  $1,
  $2,
  $3::numeric,
  $4
)
RETURNING id, branch_id, user_id, total, payment_method, status, created_at
`

type CreateSaleParams struct {
	BranchID      string        `json:"branch_id"`
	UserID        string        `json:"user_id"`
	Total         string        `json:"total"`
	PaymentMethod PaymentMethod `json:"payment_method"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.BranchID,
		arg.UserID,
		arg.Total,
		arg.PaymentMethod,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.UserID,
		&i.Total,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createSaleItem = `-- name: CreateSaleItem :one
INSERT INTO sale_items (sale_id, product_id, product_name, unit_price, quantity, subtotal)
VALUES (
  $1,
  $2,
  $3,
  $4::numeric,
  $5,
  $6::numeric
)
RETURNING id, sale_id, product_id, product_name, unit_price, quantity, subtotal
`

type CreateSaleItemParams struct {
	SaleID      string `json:"sale_id"`
	ProductID   string `json:"product_id"`
	ProductName string `json:"product_name"`
	UnitPrice   string `json:"unit_price"`
	Quantity    int32  `json:"quantity"`
	Subtotal    string `json:"subtotal"`
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.ProductName,
		arg.UnitPrice,
		arg.Quantity,
		arg.Subtotal,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.ProductName,
		&i.UnitPrice,
		&i.Quantity,
		&i.Subtotal,
	)
	return i, err
}

const decrementInventory = `-- name: DecrementInventory :one
UPDATE inventory
SET current_stock = current_stock - $1,
    updated_at    = now()
WHERE product_id    = $2
  AND branch_id     = $3
  AND current_stock >= $1
RETURNING id, product_id, branch_id, current_stock, min_stock, updated_at
`

type DecrementInventoryParams struct {
	Qty       int32  `json:"qty"`
	ProductID string `json:"product_id"`
	BranchID  string `json:"branch_id"`
}

// La condición current_stock >= qty garantiza que nunca bajamos de cero.
// Si no hay stock suficiente, devuelve pgx.ErrNoRows (detectado como ErrInsufficientStock).
func (q *Queries) DecrementInventory(ctx context.Context, arg DecrementInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, decrementInventory, arg.Qty, arg.ProductID, arg.BranchID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.CurrentStock,
		&i.MinStock,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryByProductBranch = `-- name: GetInventoryByProductBranch :one

SELECT id, product_id, branch_id, current_stock, min_stock, updated_at
FROM inventory
WHERE product_id = $1 AND branch_id = $2
`

type GetInventoryByProductBranchParams struct {
	ProductID string `json:"product_id"`
	BranchID  string `json:"branch_id"`
}

// Queries para el recurso sales (ventas) e inventory (stock).
func (q *Queries) GetInventoryByProductBranch(ctx context.Context, arg GetInventoryByProductBranchParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByProductBranch, arg.ProductID, arg.BranchID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.CurrentStock,
		&i.MinStock,
		&i.UpdatedAt,
	)
	return i, err
}

const getSale = `-- name: GetSale :one
SELECT id, branch_id, user_id, total, payment_method, status, created_at
FROM sales
WHERE id = $1
`

func (q *Queries) GetSale(ctx context.Context, id string) (Sale, error) {
	row := q.db.QueryRow(ctx, getSale, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.UserID,
		&i.Total,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSaleItems = `-- name: GetSaleItems :many
SELECT id, sale_id, product_id, product_name, unit_price, quantity, subtotal
FROM sale_items
WHERE sale_id = $1
ORDER BY id
`

func (q *Queries) GetSaleItems(ctx context.Context, saleID string) ([]SaleItem, error) {
	rows, err := q.db.Query(ctx, getSaleItems, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleItem
	for rows.Next() {
		var i SaleItem
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.ProductName,
			&i.UnitPrice,
			&i.Quantity,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT id, branch_id, user_id, total, payment_method, status, created_at
FROM sales
WHERE ($2::uuid IS NULL OR branch_id = $2)
ORDER BY created_at DESC
LIMIT $1
`

type ListSalesParams struct {
	Limit    int32   `json:"limit"`
	BranchID *string `json:"branch_id"`
}

func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error) {
	rows, err := q.db.Query(ctx, listSales, arg.Limit, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sale
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.UserID,
			&i.Total,
			&i.PaymentMethod,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
